### ISSUE TITLE
How can I get the Hounsfield units with the given float values in abdominal CTs

### ISSUE THREAD

**Issue by duducheng** [MIC-DKFZ/mood#2]
Dear organizers,

Thank you for the great challenge datasets!

I notice that in the abdominal CTs, the array values are float in [0,1] instead of int as Hounsfield units, which is the first time for me to get this kind of data. Though I could visualize it with 3D slicer or ITK snap, I still wonder the window level and window size used to convert HU into 0~1?

Or can I get the window level and window size in the nifti header? 

Thank you very much!

Jiancheng Yang

**Comment by dzimmerer** [comment]
Hi,

I'm sorry but I can not tell you any details regarding our preprocessing. 

I hope this will not present you with any problems.

Cheers,
David
